"""add_product_display_fields

Revision ID: cdd97fee60ff
Revises: 3b76c8f38d21
Create Date: 2026-02-13 14:39:28.178493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd97fee60ff'
down_revision: Union[str, Sequence[str], None] = '3b76c8f38d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_category_is_veg'), table_name='products')
    op.drop_index(op.f('ix_products_is_bestseller'), table_name='products')
    op.drop_index(op.f('ix_products_is_new_arrival'), table_name='products')
    op.drop_index(op.f('ix_products_is_veg'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_is_veg'), 'products', ['is_veg'], unique=False)
    op.create_index(op.f('ix_products_is_new_arrival'), 'products', ['is_new_arrival'], unique=False)
    op.create_index(op.f('ix_products_is_bestseller'), 'products', ['is_bestseller'], unique=False)
    op.create_index(op.f('ix_products_category_is_veg'), 'products', ['category', 'is_veg'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###
