import { Product } from './store'

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Mango Pickle',
    description: 'Authentic Andhra mango pickle with traditional spices.',
    price: 250,
    image: '🥭',
    category: 'pickle',
    type: 'veg',
    special: 'bestseller',
    inStock: true,
    stock: 50,
  },
  {
    id: 2,
    name: 'Gundu Pickle',
    description: 'Traditional gundu chilli pickle from the Godavari region.',
    price: 300,
    image: '🌶️',
    category: 'pickle',
    type: 'veg',
    inStock: true,
    stock: 30,
  },
  {
    id: 3,
    name: 'Avakaya Pickle',
    description: 'Classic Andhra avakaya with bold mango and spice.',
    price: 350,
    image: '🥒',
    category: 'pickle',
    type: 'veg',
    special: 'bestseller',
    inStock: true,
    stock: 25,
  },
  {
    id: 4,
    name: 'Mixed Pickle',
    description: 'A tangy mix of mango and lemon pickle.',
    price: 280,
    image: '🍋',
    category: 'pickle',
    type: 'veg',
    inStock: true,
    stock: 40,
  },
  {
    id: 5,
    name: 'Garam Masala',
    description: 'Aromatic spice blend for everyday cooking.',
    price: 150,
    image: '🫚',
    category: 'spice',
    type: 'veg',
    inStock: true,
    stock: 60,
  },
  {
    id: 6,
    name: 'Kashmiri Chilli Powder',
    description: 'Bright red chilli powder for colour and gentle heat.',
    price: 180,
    image: '🔴',
    category: 'spice',
    type: 'veg',
    inStock: true,
    stock: 45,
  },
  {
    id: 7,
    name: 'Turmeric Powder',
    description: 'Pure turmeric packed for freshness and daily use.',
    price: 120,
    image: '🟡',
    category: 'spice',
    type: 'veg',
    special: 'new-arrival',
    inStock: true,
    stock: 55,
  },
  {
    id: 8,
    name: 'Besan Laddu',
    description: 'Traditional gram flour laddu with rich roasted flavour.',
    price: 200,
    image: '🍬',
    category: 'laddu',
    type: 'veg',
    inStock: true,
    stock: 35,
  },
  {
    id: 9,
    name: 'Rava Laddu',
    description: 'Soft semolina laddu finished with nuts and ghee.',
    price: 220,
    image: '🟠',
    category: 'laddu',
    type: 'veg',
    special: 'bestseller',
    inStock: true,
    stock: 30,
  },
  {
    id: 10,
    name: 'Pickle Combo',
    description: 'A curated box of three customer-favourite pickles.',
    price: 750,
    image: '🎁',
    category: 'combo',
    type: 'veg',
    inStock: true,
    stock: 20,
  },
  {
    id: 11,
    name: 'Spice Combo',
    description: 'Essential kitchen spices in one easy bundle.',
    price: 500,
    image: '📦',
    category: 'combo',
    type: 'veg',
    inStock: true,
    stock: 25,
  },
  {
    id: 12,
    name: 'Sweet Combo',
    description: 'Festival-ready assorted laddus in a gift pack.',
    price: 600,
    image: '🎀',
    category: 'combo',
    type: 'veg',
    special: 'new-arrival',
    inStock: true,
    stock: 15,
  },
]
